.TH "C:/Users/Squaria/Documents/openPOWERLINK_V2_CAC/apps/CAC_CN/include/configDefine.h" 3 "Version 1.1" "CAC_CN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Squaria/Documents/openPOWERLINK_V2_CAC/apps/CAC_CN/include/configDefine.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCYCLE_LEN\fP   10000"
.br
.ti -1c
.RI "#define \fBNB_NODES\fP   3"
.br
.ti -1c
.RI "#define \fBIP_ADDR\fP   0xc0a801A6"
.br
.ti -1c
.RI "#define \fBDEFAULT_GATEWAY\fP   0xC0A801FE"
.br
.ti -1c
.RI "#define \fBSUBNET_MASK\fP   0xFFFFFF00"
.br
.ti -1c
.RI "#define \fBDEVNAME\fP   'eth0'"
.br
.ti -1c
.RI "#define \fBCOMPUTED_PI_OUT_SIZE\fP   152"
.br
.ti -1c
.RI "#define \fBSIZE_OUT\fP   75"
.br
.ti -1c
.RI "#define \fBCOMPUTED_PI_IN_SIZE\fP   80"
.br
.ti -1c
.RI "#define \fBSIZE_IN\fP   39"
.br
.ti -1c
.RI "#define \fBIIOSYSPATH\fP   '/sys/bus/iio/devices/iio:device0/'"
.br
.ti -1c
.RI "#define \fBMAX_SENSORS\fP   8"
.br
.ti -1c
.RI "#define \fBADC_READ_ERROR\fP   \-100000"
.br
.ti -1c
.RI "#define \fBCHIP_PATH\fP   '/dev/gpiochip0'"
.br
.ti -1c
.RI "#define \fBMAX_VALVES\fP   12"
.br
.ti -1c
.RI "#define \fBMAX_PATH_LENGTH\fP   1024"
.br
.ti -1c
.RI "#define \fBMAX_LINE_SIZE\fP   2832"
.br
.ti -1c
.RI "#define \fBMAX_PHYSICAL_LINE_SIZE\fP   1024"
.br
.ti -1c
.RI "#define \fBMAX_ROWS\fP   5"
.br
.ti -1c
.RI "#define \fBSTATE_CSV_DIRECTORY\fP   '\&.\&./\&.\&./\&.\&./common/commonCSVFiles/stateCSV/'"
.br
.ti -1c
.RI "#define \fBPHYSICAL_CONFIG_VANNES_DIRECTORY\fP   '\&.\&./\&.\&./include/physicalCONFIG/physicalCONFIG_valves\&.csv'"
.br
.ti -1c
.RI "#define \fBPHYSICAL_CONFIG_SENSORS_DIRECTORY\fP   '\&.\&./\&.\&./include/physicalCONFIG/physicalCONFIG_sensors\&.csv'"
.br
.ti -1c
.RI "#define \fBCOMMON_PHYSICAL_CONFIG_DIRECTORY\fP   '\&.\&./\&.\&./\&.\&./common/commonCSVFiles/activation\&.csv'"
.br
.ti -1c
.RI "#define \fBEG_ETAT_DIRECTORY\fP   '\&.\&./\&.\&./\&.\&./common/commonCSVFiles/liaisonEGEtat\&.csv'"
.br
.ti -1c
.RI "#define \fBTELEMFILES_DIRECTORY\fP   '\&.\&./\&.\&./include/telemFiles/'"
.br
.ti -1c
.RI "#define \fBEVENTLOG_MAX_LENGTH\fP   1024"
.br
.ti -1c
.RI "#define \fBDELAYMSINIT\fP   2000"
.br
.ti -1c
.RI "#define \fBDELAYMSCONTROL\fP   30"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ADC_READ_ERROR   \-100000"

.PP
Definition at line \fB22\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define CHIP_PATH   '/dev/gpiochip0'"

.PP
Definition at line \fB25\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define COMMON_PHYSICAL_CONFIG_DIRECTORY   '\&.\&./\&.\&./\&.\&./common/commonCSVFiles/activation\&.csv'"

.PP
Definition at line \fB46\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define COMPUTED_PI_IN_SIZE   80"

.PP
Definition at line \fB16\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define COMPUTED_PI_OUT_SIZE   152"

.PP
Definition at line \fB14\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define CYCLE_LEN   10000"

.PP
Definition at line \fB5\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define DEFAULT_GATEWAY   0xC0A801FE"

.PP
Definition at line \fB8\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define DELAYMSCONTROL   30"

.PP
Definition at line \fB57\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define DELAYMSINIT   2000"

.PP
Definition at line \fB56\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define DEVNAME   'eth0'"

.PP
Definition at line \fB11\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define EG_ETAT_DIRECTORY   '\&.\&./\&.\&./\&.\&./common/commonCSVFiles/liaisonEGEtat\&.csv'"

.PP
Definition at line \fB47\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define EVENTLOG_MAX_LENGTH   1024"

.PP
Definition at line \fB53\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define IIOSYSPATH   '/sys/bus/iio/devices/iio:device0/'"

.PP
Definition at line \fB20\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define IP_ADDR   0xc0a801A6"

.PP
Definition at line \fB7\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define MAX_LINE_SIZE   2832"

.PP
Definition at line \fB30\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define MAX_PATH_LENGTH   1024"

.PP
Definition at line \fB29\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define MAX_PHYSICAL_LINE_SIZE   1024"

.PP
Definition at line \fB31\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define MAX_ROWS   5"

.PP
Definition at line \fB32\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define MAX_SENSORS   8"

.PP
Definition at line \fB21\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define MAX_VALVES   12"

.PP
Definition at line \fB26\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define NB_NODES   3"

.PP
Definition at line \fB6\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define PHYSICAL_CONFIG_SENSORS_DIRECTORY   '\&.\&./\&.\&./include/physicalCONFIG/physicalCONFIG_sensors\&.csv'"

.PP
Definition at line \fB45\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define PHYSICAL_CONFIG_VANNES_DIRECTORY   '\&.\&./\&.\&./include/physicalCONFIG/physicalCONFIG_valves\&.csv'"

.PP
Definition at line \fB44\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define SIZE_IN   39"

.PP
Definition at line \fB17\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define SIZE_OUT   75"

.PP
Definition at line \fB15\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define STATE_CSV_DIRECTORY   '\&.\&./\&.\&./\&.\&./common/commonCSVFiles/stateCSV/'"

.PP
Definition at line \fB43\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define SUBNET_MASK   0xFFFFFF00"

.PP
Definition at line \fB9\fP of file \fBconfigDefine\&.h\fP\&.
.SS "#define TELEMFILES_DIRECTORY   '\&.\&./\&.\&./include/telemFiles/'"

.PP
Definition at line \fB49\fP of file \fBconfigDefine\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CAC_CN from the source code\&.
