.TH "dataEG" 3 "Version 1.2" "CAC main program" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dataEG \- struct containing the general state code according to the name of a general state CSV file taken from 'liaisonEGEtat\&.csv'  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
struct containing the general state code according to the name of a general state CSV file taken from 'liaisonEGEtat\&.csv' 

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC main program from the source code\&.
