.TH "dataActivation" 3 "Version 1.1" "CAC_CN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dataActivation \- struct containing the boolean values taken from 'activation\&.csv'  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
struct containing the boolean values taken from 'activation\&.csv' 

struct containing the general state code according to the name of a general state CSV file taken from 'liaisonEGEtat\&.csv' 

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC_CN from the source code\&.
