.TH "dataActivation" 3 "Version 1.2" "CAC main program" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dataActivation \- struct containing the boolean values taken from 'activation\&.csv'  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
struct containing the boolean values taken from 'activation\&.csv' 

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC main program from the source code\&.
