.TH "dataPhysicalConfigVannes" 3 "Version 1.2" "CAC main program" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dataPhysicalConfigVannes \- struct containing values taken from 'physicalCONFIG_valves\&.csv' such as the initial values, GPIO ports of each valves\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
struct containing values taken from 'physicalCONFIG_valves\&.csv' such as the initial values, GPIO ports of each valves\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC main program from the source code\&.
