.TH "dataPhysicalConfigSensors" 3 "Version 1.2" "CAC main program" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dataPhysicalConfigSensors \- struct containing values taken from 'physicalCONFIG_sensors\&.csv' such as the type and modbus parameters of each sensors\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
struct containing values taken from 'physicalCONFIG_sensors\&.csv' such as the type and modbus parameters of each sensors\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC main program from the source code\&.
