.TH "dataPhysicalConfigSensors" 3 "Version 1.1" "CAC_CN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dataPhysicalConfigSensors \- struct containing values taken from 'physicalCONFIG_sensors\&.csv' such as the calibrated, min and max values of each sensors\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
struct containing values taken from 'physicalCONFIG_sensors\&.csv' such as the calibrated, min and max values of each sensors\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC_CN from the source code\&.
