.TH "dataEtats" 3 "Version 1.2" "CAC main program" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dataEtats \- struct containing values taken from a general state CSV such as the value, dependance and timer dependance of each valves\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
struct containing values taken from a general state CSV such as the value, dependance and timer dependance of each valves\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC main program from the source code\&.
