.TH "LigneCSV" 3 "Version 1.1" "CAC_CN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LigneCSV
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <csv\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvaleur\fP [\fBMAX_LINE_SIZE\fP]"
.br
.ti -1c
.RI "int \fBdependanceVannes\fP [\fBMAX_LINE_SIZE\fP][\fBMAX_VALVES\fP]"
.br
.ti -1c
.RI "double \fBtimerVannes\fP [\fBMAX_LINE_SIZE\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBcsv\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int LigneCSV::dependanceVannes[\fBMAX_LINE_SIZE\fP][\fBMAX_VALVES\fP]"

.PP
Definition at line \fB25\fP of file \fBcsv\&.h\fP\&.
.SS "double LigneCSV::timerVannes[\fBMAX_LINE_SIZE\fP]"

.PP
Definition at line \fB26\fP of file \fBcsv\&.h\fP\&.
.SS "int LigneCSV::valeur[\fBMAX_LINE_SIZE\fP]"

.PP
Definition at line \fB24\fP of file \fBcsv\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC_CN from the source code\&.
