.TH "LigneSensors" 3 "Version 1.2" "CAC main program" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LigneSensors \- struct containing values taken from 'physicalCONFIG_sensors\&.csv' such as the type and modbus parameters of each sensors\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <csv\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBtype\fP [2 *\fBMAX_SENSORS\fP]"
.br
.ti -1c
.RI "uint16_t \fBmodbusAddrRemoteSlave\fP [2 *\fBMAX_SENSORS\fP]"
.br
.ti -1c
.RI "uint16_t \fBmodbusStartAddress\fP [2 *\fBMAX_SENSORS\fP]"
.br
.ti -1c
.RI "uint32_t \fBmodbusBaudRate\fP [2 *\fBMAX_SENSORS\fP]"
.br
.ti -1c
.RI "char \fBmodbusParity\fP [2 *\fBMAX_SENSORS\fP]"
.br
.ti -1c
.RI "uint16_t \fBmodbusDataBits\fP [2 *\fBMAX_SENSORS\fP]"
.br
.ti -1c
.RI "uint16_t \fBmodbusStopBit\fP [2 *\fBMAX_SENSORS\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
struct containing values taken from 'physicalCONFIG_sensors\&.csv' such as the type and modbus parameters of each sensors\&. 
.PP
Definition at line \fB67\fP of file \fBcsv\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t LigneSensors::modbusAddrRemoteSlave[2 *\fBMAX_SENSORS\fP]"
the connected sensor address 
.PP
Definition at line \fB69\fP of file \fBcsv\&.h\fP\&.
.SS "uint32_t LigneSensors::modbusBaudRate[2 *\fBMAX_SENSORS\fP]"
the modbus connexion baud rate 
.PP
Definition at line \fB71\fP of file \fBcsv\&.h\fP\&.
.SS "uint16_t LigneSensors::modbusDataBits[2 *\fBMAX_SENSORS\fP]"
the modbus databits number (5,6,7 or 8) 
.PP
Definition at line \fB73\fP of file \fBcsv\&.h\fP\&.
.SS "char LigneSensors::modbusParity[2 *\fBMAX_SENSORS\fP]"
the modbus parity (N for None, E for Even and O for Odd) 
.PP
Definition at line \fB72\fP of file \fBcsv\&.h\fP\&.
.SS "uint16_t LigneSensors::modbusStartAddress[2 *\fBMAX_SENSORS\fP]"
the read start address 
.PP
Definition at line \fB70\fP of file \fBcsv\&.h\fP\&.
.SS "uint16_t LigneSensors::modbusStopBit[2 *\fBMAX_SENSORS\fP]"
the modbus stopbit number (1 or 2) 
.PP
Definition at line \fB74\fP of file \fBcsv\&.h\fP\&.
.SS "uint8_t LigneSensors::type[2 *\fBMAX_SENSORS\fP]"
the type of sensor (1 for an MCP3008 channel and 2 for modbus) 
.PP
Definition at line \fB68\fP of file \fBcsv\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC main program from the source code\&.
