.TH "LigneCSV" 3 "Version 1.2" "CAC main program" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LigneCSV \- struct containing values taken from a general state CSV such as the value, dependance and timer dependance of each valves\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <csv\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvaleur\fP [\fBMAX_LINE_SIZE\fP]"
.br
.ti -1c
.RI "int \fBdependanceVannes\fP [\fBMAX_LINE_SIZE\fP][\fBMAX_VALVES\fP]"
.br
.ti -1c
.RI "double \fBtimerVannes\fP [\fBMAX_LINE_SIZE\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
struct containing values taken from a general state CSV such as the value, dependance and timer dependance of each valves\&. 
.PP
Definition at line \fB44\fP of file \fBcsv\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int LigneCSV::dependanceVannes[\fBMAX_LINE_SIZE\fP][\fBMAX_VALVES\fP]"
the valve dependances array 
.PP
Definition at line \fB46\fP of file \fBcsv\&.h\fP\&.
.SS "double LigneCSV::timerVannes[\fBMAX_LINE_SIZE\fP]"
the timer after which the valve is triggered 
.PP
Definition at line \fB47\fP of file \fBcsv\&.h\fP\&.
.SS "int LigneCSV::valeur[\fBMAX_LINE_SIZE\fP]"
the set value of a valve 
.PP
Definition at line \fB45\fP of file \fBcsv\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC main program from the source code\&.
