.TH "LigneEG" 3 "Version 1.1" "CAC_CN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LigneEG
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <csv\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int16_t \fBEG\fP [\fBMAX_LINE_SIZE\fP]"
.br
.ti -1c
.RI "char * \fBnom\fP [\fBMAX_LINE_SIZE\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB44\fP of file \fBcsv\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int16_t LigneEG::EG[\fBMAX_LINE_SIZE\fP]"

.PP
Definition at line \fB45\fP of file \fBcsv\&.h\fP\&.
.SS "char* LigneEG::nom[\fBMAX_LINE_SIZE\fP]"

.PP
Definition at line \fB46\fP of file \fBcsv\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC_CN from the source code\&.
