.TH "opl" 3 "Version 1.2" "CAC main program" \" -*- nroff -*-
.ad l
.nh
.SH NAME
opl \- OpenPOWERLINK module class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <opl\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBopl\fP ()"
.br
.ti -1c
.RI "\fB~opl\fP ()"
.br
.ti -1c
.RI "void \fBsendTelem\fP (int16_t statusCode)"
.br
.RI "function to send the current status code to the MN in the board state (EC) object "
.ti -1c
.RI "void \fBsendError\fP (int16_t errorCode)"
.br
.RI "function to send the current error code to the MN in the board state (EC) object "
.ti -1c
.RI "\fBstatusErrDef\fP \fBdemandeExtinctOPL\fP ()"
.br
.RI "function to check if a stop order has been received from the master node (MN) "
.in -1c
.SH "Detailed Description"
.PP 
OpenPOWERLINK module class\&. 
.PP
Definition at line \fB129\fP of file \fBopl\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "opl::opl ()"

.PP
Definition at line \fB86\fP of file \fBopl\&.cpp\fP\&.
.SS "opl::~opl ()"

.PP
Definition at line \fB91\fP of file \fBopl\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBstatusErrDef\fP opl::demandeExtinctOPL ()"

.PP
function to check if a stop order has been received from the master node (MN) 
.PP
\fBReturns\fP
.RS 4
statusErrDef infoStopOrderReceived if a stop order has been received or infoNoStopOrder if no stop order has been received 
.RE
.PP

.PP
Definition at line \fB103\fP of file \fBopl\&.cpp\fP\&.
.SS "void opl::sendError (int16_t errorCode)"

.PP
function to send the current error code to the MN in the board state (EC) object 
.PP
\fBParameters\fP
.RS 4
\fIerrorCode\fP the current error code 
.RE
.PP

.PP
Definition at line \fB129\fP of file \fBopl\&.cpp\fP\&.
.SS "void opl::sendTelem (int16_t statusCode)"

.PP
function to send the current status code to the MN in the board state (EC) object 
.PP
\fBParameters\fP
.RS 4
\fIstatusCode\fP the current status code 
.RE
.PP

.PP
Definition at line \fB118\fP of file \fBopl\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC main program from the source code\&.
