.TH "PI_IN" 3 "Version 1.2" "CAC main program" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PI_IN \- \fBPI_IN\fP contains the RPDOs (Received Process Data Object) so the OpenPOWERLINK values coming from the MN (Master Node) to the CN\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <xapOpl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int16_t \fBin_CN_array\fP [\fBSIZE_IN\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBPI_IN\fP contains the RPDOs (Received Process Data Object) so the OpenPOWERLINK values coming from the MN (Master Node) to the CN\&. 
.PP
Definition at line \fB43\fP of file \fBxapOpl\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int16_t PI_IN::in_CN_array[\fBSIZE_IN\fP]"
the array of OpenPOWERLINK values coming from the MN 
.PP
Definition at line \fB45\fP of file \fBxapOpl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC main program from the source code\&.
