.TH "sensor" 3 "Version 1.1" "CAC_CN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sensor \- sensor module class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sensor\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsensor\fP ()"
.br
.ti -1c
.RI "virtual \fB~sensor\fP ()"
.br
.ti -1c
.RI "\fBstatusErrDef\fP \fBinitSensor\fP ()"
.br
.RI "function to initialize the sensor module\&. "
.ti -1c
.RI "\fBstatusErrDef\fP \fBextinctSensor\fP ()"
.br
.RI "function to shutdown the sensor module\&. "
.in -1c
.SH "Detailed Description"
.PP 
sensor module class\&. 
.PP
Definition at line \fB43\fP of file \fBsensor\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sensor::sensor ()"

.PP
Definition at line \fB20\fP of file \fBsensor\&.cpp\fP\&.
.SS "sensor::~sensor ()\fR [virtual]\fP"

.PP
Definition at line \fB27\fP of file \fBsensor\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBstatusErrDef\fP sensor::extinctSensor ()"

.PP
function to shutdown the sensor module\&. 
.PP
\fBReturns\fP
.RS 4
statusErrDef that values errCloseAdc when a sysfs file of the MCP3008 fails to close or noError when the function exits successfully\&. 
.RE
.PP

.PP
Definition at line \fB61\fP of file \fBsensor\&.cpp\fP\&.
.SS "\fBstatusErrDef\fP sensor::initSensor ()"

.PP
function to initialize the sensor module\&. 
.PP
\fBReturns\fP
.RS 4
statusErrDef that values errOpenAdc when a sysfs file of the MCP3008 fails to open or errReadAdc when a sysfs file read of the MCP3008 fails or noError when the function exits successfully\&. 
.RE
.PP

.PP
Definition at line \fB40\fP of file \fBsensor\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC_CN from the source code\&.
