.TH "tOptions" 3 "Version 1.1" "CAC_CN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tOptions
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <opl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT32 \fBnodeId\fP"
.br
.ti -1c
.RI "tEventlogFormat \fBlogFormat\fP"
.br
.ti -1c
.RI "UINT32 \fBlogLevel\fP"
.br
.ti -1c
.RI "UINT32 \fBlogCategory\fP"
.br
.ti -1c
.RI "char \fBdevName\fP [128]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB47\fP of file \fBopl\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char tOptions::devName[128]"

.PP
Definition at line \fB53\fP of file \fBopl\&.h\fP\&.
.SS "UINT32 tOptions::logCategory"

.PP
Definition at line \fB52\fP of file \fBopl\&.h\fP\&.
.SS "tEventlogFormat tOptions::logFormat"

.PP
Definition at line \fB50\fP of file \fBopl\&.h\fP\&.
.SS "UINT32 tOptions::logLevel"

.PP
Definition at line \fB51\fP of file \fBopl\&.h\fP\&.
.SS "UINT32 tOptions::nodeId"

.PP
Definition at line \fB49\fP of file \fBopl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC_CN from the source code\&.
