.TH "C:/Users/Squaria/Documents/openPOWERLINK_V2_CAC/apps/OBC_MN/include/file.h" 3 "Version 1.2" "OpenPOWERLINK MN application for CAC boards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Squaria/Documents/openPOWERLINK_V2_CAC/apps/OBC_MN/include/file.h \- header file of the file module that writes telemetry into a file  

.SH SYNOPSIS
.br
.PP
\fR#include 'eventOpl\&.h'\fP
.br
\fR#include 'configDefine\&.h'\fP
.br
\fR#include 'statusErrorDefine\&.h'\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <ctime>\fP
.br
\fR#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBfile\fP"
.br
.RI "file module class\&. "
.in -1c
.SH "Detailed Description"
.PP 
header file of the file module that writes telemetry into a file 


.PP
\fBAuthor\fP
.RS 4
Mael Parot, Julien Mindze 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.2 
.RE
.PP
\fBDate\fP
.RS 4
11/04/2024
.RE
.PP
Contains all functions definitions related to writing the telemetry into a file named after the current date and time\&. 
.PP
Definition in file \fBfile\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenPOWERLINK MN application for CAC boards from the source code\&.
