.TH "C:/Users/Squaria/Documents/openPOWERLINK_V2_CAC/apps/OBC_MN/include/opl.h" 3 "Version 1.1" "CAC_MN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Squaria/Documents/openPOWERLINK_V2_CAC/apps/OBC_MN/include/opl.h
.SH SYNOPSIS
.br
.PP
\fR#include 'xapOpl\&.h'\fP
.br
\fR#include 'eventOpl\&.h'\fP
.br
\fR#include 'configDefine\&.h'\fP
.br
\fR#include 'statusErrorDefine\&.h'\fP
.br
\fR#include 'csv\&.h'\fP
.br
\fR#include <oplk/oplk\&.h>\fP
.br
\fR#include <oplk/debugstr\&.h>\fP
.br
\fR#include <obdpi\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include <system/system\&.h>\fP
.br
\fR#include <obdcreate/obdcreate\&.h>\fP
.br
\fR#include <getopt/getopt\&.h>\fP
.br
\fR#include <console/console\&.h>\fP
.br
\fR#include <eventlog/eventlog\&.h>\fP
.br
\fR#include <firmwaremanager/firmwaremanager\&.h>\fP
.br
\fR#include <netselect/netselect\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <limits\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtOptions\fP"
.br
.ti -1c
.RI "struct \fBtDemoNodeInfo\fP"
.br
.ti -1c
.RI "class \fBopl\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBstatusErrDef\fP \fBinitPowerlink\fP (UINT32 cycleLen_p, const char *cdcFileName_p, const char *devName_p, const UINT8 *macAddr_p)"
.br
.RI "Initialize the openPOWERLINK stack\&. "
.ti -1c
.RI "\fBstatusErrDef\fP \fBinitOplThread\fP (void)"
.br
.RI "
.br
 "
.ti -1c
.RI "\fBstatusErrDef\fP \fBinitProcessImage\fP (void)"
.br
.RI "Initialize process image\&. "
.ti -1c
.RI "\fBstatusErrDef\fP \fBshutdownOplImage\fP (void)"
.br
.RI "Shutdown the synchronous data application\&. "
.ti -1c
.RI "\fBstatusErrDef\fP \fBcheckStateOpl\fP ()"
.br
.RI "function to check if the OpenPOWERLINK stack crashed or a termination signal has been received from the OS app manager\&. "
.ti -1c
.RI "void \fBshutdownPowerlink\fP (void)"
.br
.RI "Shutdown the demo application\&. "
.ti -1c
.RI "tOplkError \fBprocessSync\fP (void)"
.br
.RI "Synchronous data handler\&. "
.ti -1c
.RI "\fBstatusErrDef\fP \fBinitApp\fP (void)"
.br
.RI "Initialize the synchronous data application\&. "
.ti -1c
.RI "\fBstatusErrDef\fP \fBinitOPL\fP ()"
.br
.RI "function to initialize the CN OpenPOWERLINK module "
.ti -1c
.RI "\fBstatusErrDef\fP \fBextinctOPL\fP ()"
.br
.RI "function to shutdown the OpenPOWERLINK module\&. "
.ti -1c
.RI "int16_t * \fBgetValues_In_MN\fP (void)"
.br
.ti -1c
.RI "void \fBsetValues_Out_MN\fP (int ligne, int16_t valeur)"
.br
.RI "function setter of the values coming out of the MN namely, the general state order and valve values in manual mode to the CNs\&. "
.ti -1c
.RI "void \fBsetActivated_In_MN\fP ()"
.br
.RI "function setter to fill the activation array from the CSV activation file 'activation\&.csv' "
.ti -1c
.RI "void \fBaffValeursIn\fP ()"
.br
.RI "function to display in the console the values coming from the CNs "
.ti -1c
.RI "void \fBaffValeursOut\fP ()"
.br
.RI "function to display in the console the values coming out of the MN "
.ti -1c
.RI "void \fBaffValeursInProcess\fP ()"
.br
.RI "function to display in the console the raw values coming from the CNs "
.ti -1c
.RI "void \fBaffValeursOutProcess\fP ()"
.br
.RI "function to display in the console the raw values coming out of the MN "
.ti -1c
.RI "void \fBchangeEG\fP ()"
.br
.RI "function to cycle through some general states to test the MN and CNs programs for the early versions\&. "
.ti -1c
.RI "void \fBsetEGToManualMode\fP ()"
.br
.RI "function to switch between automatic and manual modes\&. "
.ti -1c
.RI "void \fBmanualActivation\fP (int nodeId, int valve)"
.br
.RI "function to set to 0 or 1 a valve value of a CN when mode is set to manual mode\&. "
.ti -1c
.RI "int16_t \fBgetEC1\fP ()"
.br
.ti -1c
.RI "void \fBsetEG\fP (int16_t EG)"
.br
.RI "function setter of the current general state (EG) "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const uint16_t \fBnbValuesCN_Out\fP"
.br
.ti -1c
.RI "const uint16_t \fBnbValuesCN_In\fP"
.br
.ti -1c
.RI "static const UINT8 \fBaMacAddr_l\fP [] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }"
.br
.ti -1c
.RI "static BOOL \fBfGsOff_l\fP"
.br
.ti -1c
.RI "static UINT \fBcnt_l\fP"
.br
.ti -1c
.RI "static \fBPI_IN\fP * \fBpProcessImageIn_l\fP"
.br
.ti -1c
.RI "static \fBPI_OUT\fP * \fBpProcessImageOut_l\fP"
.br
.ti -1c
.RI "static int16_t \fBvalues_In_MN_l\fP [\fBSIZE_OUT\fP]"
.br
.ti -1c
.RI "static int16_t \fBvalues_Out_MN_l\fP [\fBSIZE_IN\fP]"
.br
.ti -1c
.RI "static bool \fBactivated_In_MN_l\fP [\fBSIZE_OUT\fP+2]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void affValeursIn ()"

.PP
function to display in the console the values coming from the CNs 
.PP
Definition at line \fB80\fP of file \fBopl\&.cpp\fP\&.
.SS "void affValeursInProcess ()"

.PP
function to display in the console the raw values coming from the CNs 
.PP
Definition at line \fB95\fP of file \fBopl\&.cpp\fP\&.
.SS "void affValeursOut ()"

.PP
function to display in the console the values coming out of the MN 
.PP
Definition at line \fB125\fP of file \fBopl\&.cpp\fP\&.
.SS "void affValeursOutProcess ()"

.PP
function to display in the console the raw values coming out of the MN 
.PP
Definition at line \fB110\fP of file \fBopl\&.cpp\fP\&.
.SS "void changeEG ()"

.PP
function to cycle through some general states to test the MN and CNs programs for the early versions\&. 
.PP
Definition at line \fB140\fP of file \fBopl\&.cpp\fP\&.
.SS "\fBstatusErrDef\fP checkStateOpl ()"

.PP
function to check if the OpenPOWERLINK stack crashed or a termination signal has been received from the OS app manager\&. 
.PP
\fBReturns\fP
.RS 4
statusErrDef that values errSystemSendTerminate if a termination signal has been received or errOplKernelStackDown if the OpenPOWERLINK stack crashed or noError when the function exits successfully\&. 
.RE
.PP

.PP
Definition at line \fB504\fP of file \fBopl\&.cpp\fP\&.
.SS "\fBstatusErrDef\fP extinctOPL ()"

.PP
function to shutdown the OpenPOWERLINK module\&. 
.PP
\fBReturns\fP
.RS 4
statusErrDef that values errOplkFreeProcessImage when the freeing of memory of the OpenPOWERLINK fails\&. or noError when the function exits successfully\&. 
.RE
.PP

.PP
Definition at line \fB662\fP of file \fBopl\&.cpp\fP\&.
.SS "int16_t getEC1 ()"

.SS "int16_t * getValues_In_MN (void)"

.PP
Definition at line \fB30\fP of file \fBopl\&.cpp\fP\&.
.SS "\fBstatusErrDef\fP initApp (void)"

.PP
Initialize the synchronous data application\&. The function initializes the synchronous data application
.PP
\fBReturns\fP
.RS 4
statusErrDef that values errOplkAllocProcessImage when the allocation of the input and/or output structure doesn't exist in the objdict\&.h file or errSetupProcessImage when the input and/or output structure are not the same with the mnobd\&.cdc file or noError when the function exits successfully\&. 
.RE
.PP

.PP
Definition at line \fB320\fP of file \fBopl\&.cpp\fP\&.
.SS "\fBstatusErrDef\fP initOPL ()"

.PP
function to initialize the CN OpenPOWERLINK module 
.PP
\fBReturns\fP
.RS 4
statusErrDef that values errOPLSystemInit when OpenPOWERLINK fails to set the correct configuration for the current operating system\&. or errInitFirmwareManager when the firmware manager to check dependances of the operating system fails to initialize or errSelNetInterface when the selection of the network interface fails when in a Windows machine can be caused by the absence of WinPcap\&. or errInitObjDictionary when the object dictionary header file (objdict\&.h) has incorrect values or syntax\&. or errOplkInit when the OpenPOWERLINK stack fails maybe because the stack is not found by the application, check the CN \&.lib files\&. or errOplkCreate when the OpenPOWERLINK stack fails to create a new instance or errOplkAllocProcessImage when the allocation of the input and/or output structure doesn't exist in the objdict\&.h file or errSendNMTResetCommand when the OpenPOWERLINK reset command fails or noError when the function exits successfully\&. 
.RE
.PP

.PP
Definition at line \fB230\fP of file \fBopl\&.cpp\fP\&.
.SS "\fBstatusErrDef\fP initOplThread (void)"

.PP

.br
 
.IP "\(bu" 2
It creates the sync thread which is responsible for the synchronous data application\&.
.PP
.PP
\fBReturns\fP
.RS 4
statusErrDef that values errSendNMTResetCommand when the OpenPOWERLINK reset command fails or noError when the function exits successfully\&. 
.RE
.PP

.PP
Definition at line \fB535\fP of file \fBopl\&.cpp\fP\&.
.SS "\fBstatusErrDef\fP initPowerlink (UINT32 cycleLen_p, const char * cdcFileName_p, const char * devName_p, const UINT8 * macAddr_p)"

.PP
Initialize the openPOWERLINK stack\&. The function initializes the openPOWERLINK stack\&.
.PP
\fBParameters\fP
.RS 4
\fIcycleLen_p\fP Length of POWERLINK cycle\&. 
.br
\fIcdcFileName_p\fP Name of the CDC file\&. 
.br
\fIdevName_p\fP Device name string\&. 
.br
\fImacAddr_p\fP MAC address to use for POWERLINK interface\&.
.RE
.PP
\fBReturns\fP
.RS 4
statusErrDef that values errSelNetInterface when the selection of the network interface fails when in a Windows machine can be caused by the absence of WinPcap\&. or errInitObjDictionary when the object dictionary header file (objdict\&.h) has incorrect values or syntax\&. or errOplkInit when the OpenPOWERLINK stack fails maybe because the stack is not found by the application, check the CN \&.lib files\&. or errOplkCreate when the OpenPOWERLINK stack fails to create a new instance or errOplkSetCDCFileName when the mnobd\&.cdc file is not found or is incorrect or noError when the function exits successfully\&. 
.RE
.PP

.PP
Definition at line \fB369\fP of file \fBopl\&.cpp\fP\&.
.SS "\fBstatusErrDef\fP initProcessImage (void)"

.PP
Initialize process image\&. The function initializes the process image of the application\&.
.PP
\fBReturns\fP
.RS 4
statusErrDef that values errOplkAllocProcessImage when the allocation of the input and/or output structure doesn't exist in the objdict\&.h file or errSetupProcessImage when the input and/or output structure are not the same with what is inside the mnobd\&.cdc file or noError when the function exits successfully\&. 
.RE
.PP

.PP
Definition at line \fB620\fP of file \fBopl\&.cpp\fP\&.
.SS "void manualActivation (int nodeId, int valve)"

.PP
function to set to 0 or 1 a valve value of a CN when mode is set to manual mode\&. 
.PP
\fBParameters\fP
.RS 4
\fInodeId\fP the id of the CN 
.br
\fIvalve\fP the valve number (from 0 to 11) 
.RE
.PP

.PP
Definition at line \fB193\fP of file \fBopl\&.cpp\fP\&.
.SS "tOplkError processSync (void)"

.PP
Synchronous data handler\&. The function implements the synchronous data handler\&.
.PP
\fBReturns\fP
.RS 4
The function returns a tOplkError error code\&. 
.RE
.PP

.PP
Definition at line \fB565\fP of file \fBopl\&.cpp\fP\&.
.SS "void setActivated_In_MN ()"

.PP
function setter to fill the activation array from the CSV activation file 'activation\&.csv' 
.PP
Definition at line \fB53\fP of file \fBopl\&.cpp\fP\&.
.SS "void setEG (int16_t EG)"

.PP
function setter of the current general state (EG) 
.PP
\fBParameters\fP
.RS 4
\fIEG\fP the current general state (EG) 
.RE
.PP

.PP
Definition at line \fB66\fP of file \fBopl\&.cpp\fP\&.
.SS "void setEGToManualMode ()"

.PP
function to switch between automatic and manual modes\&. 
.PP
Definition at line \fB170\fP of file \fBopl\&.cpp\fP\&.
.SS "void setValues_Out_MN (int ligne, int16_t valeur)"

.PP
function setter of the values coming out of the MN namely, the general state order and valve values in manual mode to the CNs\&. 
.PP
\fBParameters\fP
.RS 4
\fIligne\fP the location in the \fBPI_IN\fP structure 
.br
\fIvaleur\fP the manual valve value to set 
.RE
.PP

.PP
Definition at line \fB43\fP of file \fBopl\&.cpp\fP\&.
.SS "\fBstatusErrDef\fP shutdownOplImage (void)"

.PP
Shutdown the synchronous data application\&. The function shuts down the synchronous data application
.PP
\fBReturns\fP
.RS 4
statusErrDef that values errOplkFreeProcessImage when the freeing of memory of the OpenPOWERLINK fails\&. or noError when the function exits successfully\&. 
.RE
.PP

.PP
Definition at line \fB684\fP of file \fBopl\&.cpp\fP\&.
.SS "void shutdownPowerlink (void)"

.PP
Shutdown the demo application\&. The function shuts down the demo application\&. 
.PP
Definition at line \fB706\fP of file \fBopl\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "bool activated_In_MN_l[\fBSIZE_OUT\fP+2]\fR [static]\fP"

.PP
Definition at line \fB103\fP of file \fBopl\&.h\fP\&.
.SS "const UINT8 aMacAddr_l[] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }\fR [static]\fP"

.PP
Definition at line \fB94\fP of file \fBopl\&.h\fP\&.
.SS "UINT cnt_l\fR [static]\fP"

.PP
Definition at line \fB97\fP of file \fBopl\&.h\fP\&.
.SS "BOOL fGsOff_l\fR [static]\fP"

.PP
Definition at line \fB95\fP of file \fBopl\&.h\fP\&.
.SS "const uint16_t nbValuesCN_In\fR [extern]\fP"

.PP
Definition at line \fB17\fP of file \fBopl\&.cpp\fP\&.
.SS "const uint16_t nbValuesCN_Out\fR [extern]\fP"

.PP
Definition at line \fB16\fP of file \fBopl\&.cpp\fP\&.
.SS "\fBPI_IN\fP* pProcessImageIn_l\fR [static]\fP"

.PP
Definition at line \fB98\fP of file \fBopl\&.h\fP\&.
.SS "\fBPI_OUT\fP* pProcessImageOut_l\fR [static]\fP"

.PP
Definition at line \fB99\fP of file \fBopl\&.h\fP\&.
.SS "int16_t values_In_MN_l[\fBSIZE_OUT\fP]\fR [static]\fP"

.PP
Definition at line \fB101\fP of file \fBopl\&.h\fP\&.
.SS "int16_t values_Out_MN_l[\fBSIZE_IN\fP]\fR [static]\fP"

.PP
Definition at line \fB102\fP of file \fBopl\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CAC_MN from the source code\&.
