.TH "opl" 3 "Version 1.1" "CAC_MN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
opl
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <opl\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBopl\fP ()"
.br
.ti -1c
.RI "\fB~opl\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB112\fP of file \fBopl\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "opl::opl ()"

.PP
Definition at line \fB19\fP of file \fBopl\&.cpp\fP\&.
.SS "opl::~opl ()"

.PP
Definition at line \fB24\fP of file \fBopl\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC_MN from the source code\&.
