.TH "PI_IN" 3 "Version 1.1" "CAC_MN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PI_IN
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <xapOpl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int16_t \fBin_MN_array\fP [\fBSIZE_IN\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBxapOpl\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int16_t PI_IN::in_MN_array[\fBSIZE_IN\fP]"

.PP
Definition at line \fB19\fP of file \fBxapOpl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC_MN from the source code\&.
