.TH "PI_OUT" 3 "Version 1.1" "CAC_MN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PI_OUT
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <xapOpl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int16_t \fBout_MN_array\fP [\fBSIZE_OUT\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBxapOpl\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int16_t PI_OUT::out_MN_array[\fBSIZE_OUT\fP]"

.PP
Definition at line \fB14\fP of file \fBxapOpl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC_MN from the source code\&.
