.TH "PI_OUT" 3 "Version 1.2" "OpenPOWERLINK MN application for CAC boards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PI_OUT \- \fBPI_OUT\fP contains the RPDOs (Received Process Data Object) so the OpenPOWERLINK values coming out of the MN (Master Node) to the CN\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <xapOpl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int16_t \fBout_MN_array\fP [\fBSIZE_OUT\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBPI_OUT\fP contains the RPDOs (Received Process Data Object) so the OpenPOWERLINK values coming out of the MN (Master Node) to the CN\&. 
.PP
Definition at line \fB32\fP of file \fBxapOpl\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int16_t PI_OUT::out_MN_array[\fBSIZE_OUT\fP]"
the array of OpenPOWERLINK values coming out of the MN 
.PP
Definition at line \fB34\fP of file \fBxapOpl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenPOWERLINK MN application for CAC boards from the source code\&.
