.TH "tDemoNodeInfo" 3 "Version 1.1" "CAC_MN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tDemoNodeInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <opl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "tNmtState \fBnodeState\fP [254]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB56\fP of file \fBopl\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "tNmtState tDemoNodeInfo::nodeState[254]"

.PP
Definition at line \fB58\fP of file \fBopl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC_MN from the source code\&.
