.TH "tEventConfig" 3 "Version 1.1" "CAC_MN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tEventConfig \- Event configuration\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <eventOpl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BOOL * \fBpfGsOff\fP"
.br
.RI "Pointer to GsOff flag (determines if the stack is down) "
.ti -1c
.RI "tOplkApiCbEvent \fBpfnFirmwareManagerCallback\fP"
.br
.RI "Callback function to firmware manager\&. "
.in -1c
.SH "Detailed Description"
.PP 
Event configuration\&. 
.PP
Definition at line \fB63\fP of file \fBeventOpl\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "BOOL* tEventConfig::pfGsOff"

.PP
Pointer to GsOff flag (determines if the stack is down) 
.PP
Definition at line \fB65\fP of file \fBeventOpl\&.h\fP\&.
.SS "tOplkApiCbEvent tEventConfig::pfnFirmwareManagerCallback"

.PP
Callback function to firmware manager\&. 
.PP
Definition at line \fB66\fP of file \fBeventOpl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC_MN from the source code\&.
