.TH "tEventInstance" 3 "Version 1.1" "CAC_MN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tEventInstance \- Event instance\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtEventConfig\fP \fBconfig\fP"
.br
.RI "Configuration provided in \fBinitEvents()\fP "
.in -1c
.SH "Detailed Description"
.PP 
Event instance\&. 
.PP
Definition at line \fB77\fP of file \fBeventOpl\&.c\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBtEventConfig\fP tEventInstance::config"

.PP
Configuration provided in \fBinitEvents()\fP 
.PP
Definition at line \fB79\fP of file \fBeventOpl\&.c\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CAC_MN from the source code\&.
