.TH "C:/Users/Squaria/Documents/openPOWERLINK_V2_CAC/apps/OBC_MN/include/xapOpl.h" 3 "Version 1.1" "CAC_MN" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Squaria/Documents/openPOWERLINK_V2_CAC/apps/OBC_MN/include/xapOpl.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include 'configDefine\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPI_OUT\fP"
.br
.ti -1c
.RI "struct \fBPI_IN\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CAC_MN from the source code\&.
