eventOpl.c
static tOplkError processStateChangeEvent(const tEventNmtStateChange *pNmtStateChange_p, void *pUserArg_p)
Process state change events.
The function processes state change events. pNmtStateChange_p Pointer to the state change structure pUserArg_p User specific argument The function returns a tOplkError error code.
References tEventInstance::config, instance_l, tEventConfig::pfGsOff.
Referenced by processEvents.
static tOplkError processErrorWarningEvent(const tEventError *pInternalError_p, void *pUserArg_p)
Process error and warning events.
The function processes error and warning events. pInternalError_p Pointer to the error structure pUserArg_p User specific argument The function returns a tOplkError error code.
Referenced by processEvents.
static tOplkError processHistoryEvent(const tErrHistoryEntry *pHistoryEntry_p, void *pUserArg_p)
Process history events.
The function processes history events. pHistoryEntry_p Pointer to the history entry pUserArg_p User specific argument The function returns a tOplkError error code.
Referenced by processEvents.
static tOplkError processNodeEvent(const tOplkApiEventNode *pNode_p, void *pUserArg_p)
Process node events.
The function processes node events. pNode_p Pointer to the node event pUserArg_p User specific argument The function returns a tOplkError error code.
Referenced by processEvents.
static tOplkError processPdoChangeEvent(const tOplkApiEventPdoChange *pPdoChange_p, void *pUserArg_p)
Process PDO change events.
The function processes PDO change events. pPdoChange_p Pointer to the PDO change event structure pUserArg_p User specific argument The function returns a tOplkError error code.
Referenced by processEvents.
static tOplkError processCfmProgressEvent(const tCfmEventCnProgress *pCfmProgress_p, void *pUserArg_p)
Process CFM progress events.
The function processes CFM progress events. pCfmProgress_p Pointer to the CFM progress information pUserArg_p User specific argument The function returns a tOplkError error code.
Referenced by processEvents.
static tOplkError processCfmResultEvent(const tOplkApiEventCfmResult *pCfmResult_p, void *pUserArg_p)
Process CFM result events.
The function processes CFM result events. pCfmResult_p Pointer to the CFM result information pUserArg_p User specific argument The function returns a tOplkError error code.
Referenced by processEvents.
static tOplkError processFirmwareManagerEvents(tOplkApiEventType eventType_p, const tOplkApiEventArg *pEventArg_p, void *pUserArg_p)
References tEventInstance::config, instance_l, tEventConfig::pfnFirmwareManagerCallback.
Referenced by processEvents.
tEventInstance instance_l
Referenced by initEvents, processFirmwareManagerEvents, processStateChangeEvent.
void initEvents(const tEventConfig *config)
Initialize applications event module.
The function initializes the applications event module pfGsOff_p Pointer to GsOff flag (determines if the stack is down)
References instance_l.
Referenced by initOPL.
tOplkError processEvents(tOplkApiEventType eventType_p, const tOplkApiEventArg *pEventArg_p, void *pUserArg_p)
Process openPOWERLINK events.
The function implements the application's stack event handler. eventType_p Type of event pEventArg_p Pointer to union which describes the event in detail pUserArg_p User specific argument The function returns a tOplkError error code.
References processCfmProgressEvent, processCfmResultEvent, processErrorWarningEvent, processFirmwareManagerEvents, processHistoryEvent, processNodeEvent, processPdoChangeEvent, processStateChangeEvent.
Referenced by initPowerlink.