/*
* This file was autogenerated by openCONFIGURATOR-2.2.1_release on 23-Nov-2023 14:59:07
* Project: ASTREOS-1_OpenPOWERLINK
* Application process for openPOWERLINK_MN(240)
*/
#ifndef XAP_h
#define XAP_h

#define COMPUTED_PI_OUT_SIZE 84
typedef struct
{
	signed CN1_AnalogueInput_00h_AI16_EC_CACMO:16;
	unsigned PADDING_VAR_1:16;
	signed CN1_AnalogueInput_00h_AI32_MEP_TP01:32;
	signed CN1_AnalogueInput_00h_AI32_MEP_PR01:32;
	signed CN1_AnalogueInput_00h_AI32_MEP_PR02:32;
	signed CN1_AnalogueInput_00h_AI32_MEP_PR03:32;
	signed CN1_AnalogueInput_00h_AI32_MEP_PR04:32;
	signed CN1_AnalogueInput_00h_AI8_E_VCE:8;
	signed CN1_AnalogueInput_00h_AI8_E_VBCE:8;
	signed CN1_AnalogueInput_00h_AI8_E_VCO:8;
	signed CN1_AnalogueInput_00h_AI8_E_VBCO:8;
	signed CN2_AnalogueInput_00h_AI16_EC_CACOE:16;
	unsigned PADDING_VAR_2:16;
	signed CN2_AnalogueInput_00h_AI32_MEP_TP02:32;
	signed CN2_AnalogueInput_00h_AI32_MEP_TP03:32;
	signed CN2_AnalogueInput_00h_AI32_MEP_PR05:32;
	signed CN2_AnalogueInput_00h_AI32_MEP_PR06:32;
	signed CN2_AnalogueInput_00h_AI32_MEP_PR07:32;
	signed CN2_AnalogueInput_00h_AI8_E_VPrO:8;
	signed CN2_AnalogueInput_00h_AI8_E_VMAO:8;
	signed CN3_AnalogueInput_00h_AI16_EC_CACEHP:16;
	signed CN3_AnalogueInput_00h_AI32_MEP_TP04:32;
	signed CN3_AnalogueInput_00h_AI32_MEP_TP05:32;
	signed CN3_AnalogueInput_00h_AI32_MEP_PR08:32;
	signed CN3_AnalogueInput_00h_AI32_MEP_PR09:32;
	signed CN3_AnalogueInput_00h_AI32_MEP_PR10:32;
	signed CN3_AnalogueInput_00h_AI8_E_VMAPr:8;
	signed CN3_AnalogueInput_00h_AI8_E_VPrG:8;
	signed CN3_AnalogueInput_00h_AI8_E_VPrE:8;
	signed CN3_AnalogueInput_00h_AI8_E_VMAE:8;
	signed CN4_AnalogueInput_00h_AI16_EC:16;
	unsigned PADDING_VAR_3:16;
} PI_OUT;

#define COMPUTED_PI_IN_SIZE 8
typedef struct
{
	signed CN1_AnalogueOutput_00h_AI16_EC:16;
	signed CN2_AnalogueOutput_00h_AI16_EC:16;
	signed CN3_AnalogueOutput_00h_AI16_EC:16;
	unsigned PADDING_VAR_1:16;
} PI_IN;

#endif
