/*
* This file was autogenerated by openCONFIGURATOR-2.2.1_release on 23-Nov-2023 14:59:07
* Project: ASTREOS-1_OpenPOWERLINK
* Application process for openPOWERLINK_MN(240)
*/
#ifndef XAP_h
#define XAP_h

#define COMPUTED_PI_OUT_SIZE 84
typedef struct
{
	INT16 CN1_AnalogueInput_00h_AI16_EC_CACMO;
	UINT16 PADDING_VAR_1;
	INT32 CN1_AnalogueInput_00h_AI32_MEP_TP01;
	INT32 CN1_AnalogueInput_00h_AI32_MEP_PR01;
	INT32 CN1_AnalogueInput_00h_AI32_MEP_PR02;
	INT32 CN1_AnalogueInput_00h_AI32_MEP_PR03;
	INT32 CN1_AnalogueInput_00h_AI32_MEP_PR04;
	INT32 CN1_AnalogueInput_00h_AI8_E_VCE;
	INT32 CN1_AnalogueInput_00h_AI8_E_VBCE;
	INT32 CN1_AnalogueInput_00h_AI8_E_VCO;
	INT32 CN1_AnalogueInput_00h_AI8_E_VBCO;
	INT16 CN2_AnalogueInput_00h_AI16_EC_CACOE;
	UINT16 PADDING_VAR_2;
	INT32 CN2_AnalogueInput_00h_AI32_MEP_TP02;
	INT32 CN2_AnalogueInput_00h_AI32_MEP_TP03;
	INT32 CN2_AnalogueInput_00h_AI32_MEP_PR05;
	INT32 CN2_AnalogueInput_00h_AI32_MEP_PR06;
	INT32 CN2_AnalogueInput_00h_AI32_MEP_PR07;
	INT32 CN2_AnalogueInput_00h_AI8_E_VPrO;
	INT32 CN2_AnalogueInput_00h_AI8_E_VMAO;
	INT16 CN3_AnalogueInput_00h_AI16_EC_CACEHP;
	INT32 CN3_AnalogueInput_00h_AI32_MEP_TP04;
	INT32 CN3_AnalogueInput_00h_AI32_MEP_TP05;
	INT32 CN3_AnalogueInput_00h_AI32_MEP_PR08;
	INT32 CN3_AnalogueInput_00h_AI32_MEP_PR09;
	INT32 CN3_AnalogueInput_00h_AI32_MEP_PR10;
	INT32 CN3_AnalogueInput_00h_AI8_E_VMAPr;
	INT32 CN3_AnalogueInput_00h_AI8_E_VPrG;
	INT32 CN3_AnalogueInput_00h_AI8_E_VPrE;
	INT32 CN3_AnalogueInput_00h_AI8_E_VMAE;
	UINT16 PADDING_VAR_3;
} PI_IN;

#define COMPUTED_PI_IN_SIZE 8
typedef struct
{
	INT16 CN1_AnalogueOutput_00h_AI16_EC;
	INT16 CN2_AnalogueOutput_00h_AI16_EC;
	INT16 CN3_AnalogueOutput_00h_AI16_EC;
	UINT16 PADDING_VAR_1;
} PI_OUT;

#endif
