.TH "LigneActivation" 3 "Version 1.2" "OpenPOWERLINK MN application for CAC boards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LigneActivation \- struct containing the boolean values taken from 'activation\&.csv'  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <csv\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBactivation\fP [\fBMAX_LINE_SIZE\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
struct containing the boolean values taken from 'activation\&.csv' 
.PP
Definition at line \fB43\fP of file \fBcsv\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t LigneActivation::activation[\fBMAX_LINE_SIZE\fP]"
the activation of a valve, sensor or board state (1 for activated, 0 otherwise) 
.PP
Definition at line \fB44\fP of file \fBcsv\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenPOWERLINK MN application for CAC boards from the source code\&.
