.TH "C:/Users/Squaria/Documents/openPOWERLINK_V2_CAC/apps/OBC_MN/include/nbNodes.h" 3 "Version 1.2" "OpenPOWERLINK MN application for CAC boards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Squaria/Documents/openPOWERLINK_V2_CAC/apps/OBC_MN/include/nbNodes.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNB_NODES\fP   3"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NB_NODES   3"

.PP
Definition at line \fB1\fP of file \fBnbNodes\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenPOWERLINK MN application for CAC boards from the source code\&.
