.TH "tDemoNodeInfo" 3 "Version 1.2" "OpenPOWERLINK MN application for CAC boards" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tDemoNodeInfo \- the OpenPOWERLINK node information structure  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <opl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "tNmtState \fBnodeState\fP [254]"
.br
.in -1c
.SH "Detailed Description"
.PP 
the OpenPOWERLINK node information structure 
.PP
Definition at line \fB77\fP of file \fBopl\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "tNmtState tDemoNodeInfo::nodeState[254]"
The current OpenPOWERLINK node state 
.PP
Definition at line \fB79\fP of file \fBopl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenPOWERLINK MN application for CAC boards from the source code\&.
