file
string file::pathFile
Referenced by initFile, openFile.
ofstream file::dataFile
Referenced by closeFile, openFile, testWriteFile, writeError, writeTelem.
string file::nameFiles
Referenced by initFile.
string file::year_month_day
Referenced by initFile.
string file::hour_minute_second
Referenced by initFile.
file::file()
file::~file()
statusErrDef file::initFile()
function to create the telemetry file and name it after the current date and time
statusErrDef that values errOpenTelemFile when the file creation and opening fails. or noError when the function exits successfully.
References hour_minute_second, nameFiles, noError, openFile, pathFile, TELEMFILES_DIRECTORY, year_month_day.
Referenced by main.
statusErrDef file::testWriteFile()
function to test if we can write in the telemetry file
statusErrDef that values errTestWriteFile when the file write fails. or noError when the function exits successfully.
References dataFile, errTestWriteFile, noError.
Referenced by main.
statusErrDef file::openFile()
function to open the telemetry file
statusErrDef that values errOpenTelemFile when the file open fails. or noError when the function exits successfully.
References dataFile, errOpenTelemFile, noError, pathFile.
Referenced by initFile.
statusErrDef file::closeFile()
function to close the telemetry file
statusErrDef that values errCloseTelemFile when the file close fails. or noError when the function exits successfully.
References dataFile, errCloseTelemFile, noError.
Referenced by main.
void file::writeTelem(const char *fmt_p,...)
ajouter uniquement : uint16_t codeSuccess
function to write status telemetry into the telemetry file. fmt_p formated string about the status ... other parameters such as the success code
References dataFile, EVENTLOG_MAX_LENGTH.
Referenced by main.
void file::writeError(const char *fmt_p="code_Error:0x%08X",...)
ajouter uniquement : uint16_t codeError
function to write error telemetry into the telemetry file. fmt_p formated string about the error ... other parameters such as the error code
References dataFile, EVENTLOG_MAX_LENGTH.
Referenced by main.