opl
opl::opl()
opl::~opl()
void opl::sendTelem(int16_t statusCode)
function to send the current status code to the MN in the board state (EC) object
statusCode the current status code
References nbValuesCN_Out_ByCN, values_Out_CN_l.
Referenced by main.
void opl::sendError(int16_t errorCode)
function to send the current error code to the MN in the board state (EC) object
errorCode the current error code
References nbValuesCN_Out_ByCN, values_Out_CN_l.
Referenced by main.
statusErrDef opl::demandeExtinctOPL()
function to check if a stop order has been received from the master node (MN)
statusErrDef infoStopOrderReceived if a stop order has been received or infoNoStopOrder if no stop order has been received
References infoNoStopOrder, infoStopOrderReceived, nbValuesCN_Out_ByCN, values_In_CN_l.
Referenced by main.