valve
valve::valve()
valve::~valve()
statusErrDef valve::initValve()
function to initialize to valve module
statusErrDef that values errGPIOPathEmpty when the gpio chip path is not correctly set or errOpenGPIO when the gpio chip fails to open or errGPIOGetLine when the gpio lines are busy, line get fails or errGPIORequestOutput when the gpio lines can't be set to output mode or noError when the function exits successfully.
References actionnementValvesInit, CHIP_PATH, errGPIOGetLine, errGPIOPathEmpty, errGPIORequestOutput, errOpenGPIO, getActivation, getEtatInitialVannes, getPortGPIO, getValvesInitValue, i, MAX_VALVES, nbValuesCN_Out_ByCN, noError, offsets, values.
Referenced by main.
statusErrDef valve::actionnementValvesInit()
function to set the valves values from the CSV module initial values.
statusErrDef that values errValueInitIsNotBinary when a value is not 0 or 1. or errGPIOSetInitValue when the line doesn't set the value or noError when the function exits successfully.
References errGPIOSetInitValue, errValueInitIsNotBinary, getActivation, i, MAX_VALVES, nbValuesCN_Out_ByCN, noError, values.
Referenced by extinctValve, initValve.
statusErrDef valve::actionnementValve(int valveNum)
function to get a valve value either from a general state CSV file if mode is automatic or from a OpenPOWERLINK value from the MN and set the valve to the corresponding gpio line.
valveNum the valve number statusErrDef that values errValueInitIsNotBinary when an initial valve value is not 0 or 1. or errGPIOSetValue when the valve value has not been set to the gpio line or noError when the function exits successfully.
References automatic, errGPIOSetValue, errValueIsNotBinary, getValeur, getValues_In_CN, manual, mode, nbValuesCN_In_ByCN, noError, values.
Referenced by verifDependanceValves.
statusErrDef valve::verifDependanceValves()
function that verifies if the valves are already set, if not the timer starts and once the timer is greater than the value taken from a general state CSV file, it sets the valve value to the corresponding gpio line.
statusErrDef that values errValueInitIsNotBinary when a value is not 0 or 1. or errGPIOSetValue when the line doesn't set the value or noError when the function exits successfully.
References actionnementValve, automatic, errGPIOGetValue, getActivation, getValeur, getValues_In_CN, i, infoAllDependNotActivated, infoNoDepend, infoValveAlreadyActivated, isDependanceActive, isTimerExeeded, manual, MAX_VALVES, mode, nbValuesCN_In_ByCN, nbValuesCN_Out_ByCN, noError, startTimerDependance, timerStarted.
Referenced by processSync.
statusErrDef valve::isDependanceActive(int ligne)
function to check if every dependance of a valve is activated according to the array of dependance from a general state CSV file.
ligne the line in the general state CSV file statusErrDef that values errGPIOGetValue when the getter of a gpio line value fails or infoValveAlreadyActivated when every dependances or errGPIODependValue when the getter of a gpio line dependance value fails or infoAllDependNotActivated when all the dependances of a valve are not activated. or errDependOutsideOfRange when a dependance is not among the valves of the same board. or infoNoDepend when the valve has no dependances. or noError when the function exits successfully.
References errDependOutsideOfRange, errGPIODependValue, errGPIOGetValue, getDependanceVannes, getValeur, i, infoAllDependNotActivated, infoNoDepend, infoValveAlreadyActivated, MAX_VALVES, nbValuesCN_In, nbValuesCN_In_ByCN, noError.
Referenced by verifDependanceValves.
int16_t valve::startTimerDependance(int ligne)
function to start the timer when all the dependances of a valve are activated.
valveNum the valve number 0 if the timer starts successfully
References beginTimer, timerStarted.
Referenced by verifDependanceValves.
int16_t valve::isTimerExeeded(int ligne)
function to check if the current value of a timer has exceeded the timer value from a general state CSV file.
valveNum the valve number 0 if the value has been exceeded, 1 if not
References beginTimer, currentTime, endTimer, getTimerVannes, nbValuesCN_In_ByCN.
Referenced by verifDependanceValves.
statusErrDef valve::extinctValve()
function to shutdown the valve module.
statusErrDef that values errValueInitIsNotBinary when a value is not 0 or 1 or errGPIOSetInitValue when an initial valve value is not set to a line or errGPIORelease when a gpio line fails to be released or noError when the function exits successfully.
References actionnementValvesInit, errGPIORelease, getActivation, getValvesInitValue, i, MAX_VALVES, nbValuesCN_Out_ByCN, noError.
Referenced by main.