csv.h
struct LigneCSV* dataEtats
struct LigneVannes* dataPhysicalConfigVannes
struct LigneSensors* dataPhysicalConfigSensors
struct LigneActivation* dataActivation
struct LigneEG* dataEG
statusErrDef initCSV()
function to initialize the struct containing the values and read the 5 different CSV files.
statusErrDef that values errAllocDataPhysValves, errAllocDataPhysSensors, errAllocDataActivation in case of a malloc allocation error or noError when the function exits successfully.
References COMMON_PHYSICAL_CONFIG_DIRECTORY, EG, errAllocDataActivation, errAllocDataPhysSensors, errAllocDataPhysValves, lireFichierActivation, lireFichierSensors, lireFichierVannes, noError, PHYSICAL_CONFIG_SENSORS_DIRECTORY, PHYSICAL_CONFIG_VANNES_DIRECTORY, refreshCSV.
Referenced by main.
statusErrDef refreshCSV()
function to get values of the new general state CSV and "liaisonEGEtat.csv"
statusErrDef that values errAllocDataEG , errAllocDataEtats, in case of a malloc allocation error or noError when the function exits successfully.
References EG, EG_ETAT_DIRECTORY, errAllocDataEG, errAllocDataEtats, lireFichierCSV, lireFichierEG, noError, STATE_CSV_DIRECTORY.
Referenced by initCSV, main.
statusErrDef extinctCSV()
function to free the 5 structs
statusErrDef noError when the function exits successfully.
References noError.
Referenced by main.
statusErrDef lireFichierCSV(const char *dir)
function to read a general state CSV file until the end of the file.
dir location of the CSV file to read statusErrDef errEGNotFoundInFile general code (EG) not found in liaisonEGEtat.csv linked with the CSV file name, errOpenEtatsFile when the file fails to open, noError when the function exits successfully.
References errEGNotFoundInFile, errOpenEtatsFile, getNomFichiercsv, MAX_LINE_SIZE, MAX_PATH_LENGTH, noError, remplirStructure.
Referenced by refreshCSV.
statusErrDef lireFichierVannes(const char *fileName)
function to read "physicalCONFIG_valves.csv" until the end of the file.
fileName location and name of the CSV file to read statusErrDef errOpenPhysValvesFile when the file fails to open, noError when the function exits successfully.
References errOpenPhysValvesFile, MAX_PHYSICAL_LINE_SIZE, noError, remplirStructureVannesPhysicalCONFIG.
Referenced by initCSV.
statusErrDef lireFichierSensors(const char *fileName)
function to read "physicalCONFIG_sensors.csv" until the end of the file.
fileName location and name of the CSV file to read statusErrDef errOpenPhysSensorsFile when the file fails to open, noError when the function exits successfully.
References errOpenPhysSensorsFile, MAX_PHYSICAL_LINE_SIZE, noError, remplirStructureSensorsPhysicalCONFIG.
Referenced by initCSV.
statusErrDef lireFichierActivation(const char *fileName)
function to read "activation.csv" until the end of the file.
fileName location and name of the CSV file to read statusErrDef errOpenPhysSensorsFile when the file fails to open, noError when the function exits successfully.
References errOpenActivationFile, MAX_LINE_SIZE, noError, remplirStructureCommon.
Referenced by initCSV.
statusErrDef lireFichierEG(const char *fileName)
function to read "liaisonEGEtat.csv" until the end of the file.
fileName location and name of the CSV file to read statusErrDef errOpenEGFile when the file fails to open, noError when the function exits successfully.
References errOpenEGFile, MAX_LINE_SIZE, noError, remplirEG.
Referenced by refreshCSV.
void remplirStructure(char *ligne, int id)
function to fill in the general CSV structure.
ligne the CSV line to read. id the position of the line in the CSV file.
References i.
Referenced by lireFichierCSV.
void remplirStructureVannesPhysicalCONFIG(char *ligne, int id)
function to fill in the physical config valves structure.
ligne the CSV line to read. id the position of the line in the CSV file.
Referenced by lireFichierVannes.
void remplirStructureSensorsPhysicalCONFIG(char *ligne, int id)
function to fill in the physical config sensors structure.
ligne the CSV line to read. id the position of the line in the CSV file.
Referenced by lireFichierSensors.
void remplirStructureCommon(char *ligne, int id)
function to fill in the activation CSV structure.
ligne the CSV line to read. id the position of the line in the CSV file.
Referenced by lireFichierActivation.
void remplirEG(char *ligne, int id)
function to fill in the link between EG and CSV file name structure.
ligne the CSV line to read. id the position of the line in the CSV file.
References removeCarriageReturn.
Referenced by lireFichierEG.
int getValeur(int ligne)
function getter of the value of valves from a general state CSV
ligne the line in the CSV file int the value of the valve from a specific line
Referenced by valve::actionnementValve, getValveValue, valve::isDependanceActive, setValvesValue, valve::verifDependanceValves.
int * getDependanceVannes(int ligne)
function getter of all the dependances for a valve from a general state CSV
ligne the line in the CSV file int* an array of all the dependances for a valve
References i, MAX_VALVES.
Referenced by valve::isDependanceActive.
double getTimerVannes(int ligne)
function getter of the timer until value is set for a valve from a general state CSV
ligne the line in the CSV file double the value of the timer
Referenced by valve::isTimerExeeded.
uint8_t getEtatInitialVannes(int ligne)
function getter of the initial value of a valve from "physicalCONFIG_valves.csv"
ligne the line in the CSV file uint8_t the initial value of the valve
Referenced by getValvesInitValue, valve::initValve.
uint8_t getPortGPIO(int ligne)
function getter of a valve GPIO port from "physicalCONFIG_valves.csv"
ligne the line in the CSV file uint8_t the GPIO port of the valve
Referenced by valve::initValve.
uint8_t getSensorType(int ligne)
function getter of a sensor type from "physicalCONFIG_sensors.csv" can be 1 for an MCP3008 channel or 2 for a modbus serial sensor.
ligne the line in the CSV file uint8_t the sensor type
Referenced by sensor::extinctSensor, sensor::initSensor, readChannels.
uint16_t getModbusAddrRemoteSlave(int ligne)
function getter of a modbus sensor address from "physicalCONFIG_sensors.csv"
ligne the line in the CSV file uint8_t the modbus sensor address
Referenced by sensor::initSensor.
uint16_t getModbusStartAddress(int ligne)
function getter of a sensor start address to read, from "physicalCONFIG_sensors.csv"
ligne the line in the CSV file uint8_t the sensor start address to read
Referenced by sensor::initSensor, readChannels.
uint16_t getModbusNbRegisters(int ligne)
uint32_t getModbusBaudRate(int ligne)
function getter of a sensor start address to read, from "physicalCONFIG_sensors.csv"
ligne the line in the CSV file uint8_t the sensor start address to read
Referenced by sensor::initSensor.
char getModbusParity(int ligne)
function getter of the modbus parity from "physicalCONFIG_sensors.csv" can be 'O' (Odd), 'E' (Even) or 'N' (None).
ligne the line in the CSV file uint8_t the modbus parity
Referenced by sensor::initSensor.
uint16_t getModbusDataBits(int ligne)
function getter of the modbus number of data bits from "physicalCONFIG_sensors.csv" can be 5,6,7 or 8.
ligne the line in the CSV file uint8_t the modbus number of data bits
Referenced by sensor::initSensor.
uint16_t getModbusStopBit(int ligne)
function getter of the modbus number of stop bits from "physicalCONFIG_sensors.csv" can be 1 or 2.
ligne the line in the CSV file uint8_t the modbus number of stop bits
Referenced by sensor::initSensor.
uint8_t getActivation(int ligne)
function getter of the activation of a sensor or a valve from "activation.csv"
ligne the line in the CSV file uint8_t the activation of a sensor or a valve (1 if activated or 0 if not)
Referenced by valve::actionnementValvesInit, valve::extinctValve, getValvesInitValue, sensor::initSensor, valve::initValve, resetTimers, setActivated_Out_CN, setValvesValue, valve::verifDependanceValves.
int16_t getEGcsv(int ligne)
function getter of the general state from "liaisonEGEtat.csv"
ligne the line in the CSV file uint16_t the value of the general state of a specific line
const char * getNomFichiercsv()
function getter of the name of a general state CSV file of the current general state (EG)
const char* the name of a general state CSV file
References searchEG.
Referenced by lireFichierCSV.
int searchEG()
search the general state (EG) from the link between EG and CSV file name structure
int the general state (EG)
References EG, i, MAX_LINE_SIZE.
Referenced by getNomFichiercsv.
void removeCarriageReturn(char *str)
function that removes the carriage return from the end a line of a general state CSV file before strdup is called.
str the line in the CSV file
References i.
Referenced by remplirEG.