opl.cpp
int16_t EG
the general state from the MN (the OBC). It is initialized to 0 so a general state CSV file with EG = 0x0000 should not exist.
Referenced by initCSV, isEGchanged, main, refreshCSV, searchEG.
int16_t EC
the board state of this CN (this CAC board). It is initialized to the copy of the general state EG.
Referenced by isEGchanged, setEC, setValues_Out_CN.
Mode mode
the mode of the program. It is initialized to the automatic mode, the general state CSV files are first used.
Referenced by valve::actionnementValve, isEGchanged, processSync, valve::verifDependanceValves.
const uint16_t nbValuesCN_Out
the number of values coming out of each CNs
Referenced by affValeursOut, initProcessImage, sensor::initSensor, processSync, setValues_Out_CN.
const uint16_t nbValuesCN_In
the number of values coming into each CNs
Referenced by getValveValue, initProcessImage, valve::isDependanceActive, processSync.
const uint16_t nbValuesCN_Out_ByCN
the first value position coming out of this CN (the position of EC)
Referenced by valve::actionnementValvesInit, affValeursOut, valve::extinctValve, getValvesInitValue, initProcessImage, sensor::initSensor, valve::initValve, processSync, resetTimers, opl::sendError, opl::sendTelem, setEC, setValues_Out_CN, setValvesValue, valve::verifDependanceValves.
const uint16_t nbValuesCN_In_ByCN
the first value position coming into this CN (the position of EG)
Referenced by valve::actionnementValve, opl::demandeExtinctOPL, getEG, initProcessImage, valve::isDependanceActive, isEGchanged, valve::isTimerExeeded, processSync, setValues_Out_CN, setValvesValue, valve::verifDependanceValves.
const UINT8 aMacAddr_l[][]
the LAN card mac address
Referenced by initOPL.
BOOL fGsOff_l
Pointer to GsOff flag (determines that OpenPOWERLINK stack is down)
Referenced by initOPL, shutdownPowerlink.
const PI_IN* pProcessImageIn_l
the TPDO process variable (coming out of the CN)
Referenced by affValeursProcessIn, initProcessImage, processSync.
PI_OUT* pProcessImageOut_l
the RPDO process variable (coming into the CN)
Referenced by initProcessImage, processSync.
int16_t values_In_CN_l[SIZE_IN][SIZE_IN]
array of incoming values from the MN
Referenced by affValeursIn, opl::demandeExtinctOPL, getEG, getValues_In_CN, isEGchanged, processSync, setupInputs.
int16_t values_Out_CN_l[SIZE_OUT][SIZE_OUT]
array of values coming out of the CN
Referenced by affValeursOut, getValues_Out_CN, processSync, opl::sendError, opl::sendTelem, setEC, setValues_Out_CN.
bool activated_Out_CN_l[SIZE_OUT+2][SIZE_OUT+2]
array of value activation coming out of the CN true if activated, false otherwise
Referenced by initProcessImage, processSync, setActivated_Out_CN, setValues_Out_CN.
void affValeursIn()
function to display in the console the values coming from the MN
References i, SIZE_IN, values_In_CN_l.
Referenced by main.
void affValeursProcessIn()
function to display in the console the values coming from the MN
References i, PI_IN::in_CN_array, pProcessImageIn_l, SIZE_IN.
Referenced by main.
void affValeursOut()
function to display in the console the values coming out of the CN
References i, nbValuesCN_Out, nbValuesCN_Out_ByCN, values_Out_CN_l.
Referenced by main.
int16_t getValues_In_CN(int ligne)
function getter of the value coming from the MN from line according to the structure PI_IN
ligne the line according to the structure PI_IN int16_t the value coming from the MN
References values_In_CN_l.
Referenced by valve::actionnementValve, valve::verifDependanceValves.
void setValues_Out_CN()
function setter of the values coming out of the CN namely, the valves and sensors values.
References activated_Out_CN_l, EC, getAdc_value, getValveValue, i, MAX_SENSORS, MAX_VALVES, nbValuesCN_In_ByCN, nbValuesCN_Out, nbValuesCN_Out_ByCN, values_Out_CN_l.
Referenced by processSync.
int16_t getValues_Out_CN(int ligne)
function getter of the value coming out of the CN from line according to the structure PI_OUT
ligne the line according to the structure PI_OUT int16_t the value coming out of the CN
References values_Out_CN_l.
void setActivated_Out_CN()
function setter to fill the activation array from the CSV activation file "activation.csv"
References activated_Out_CN_l, getActivation, i, SIZE_OUT.
Referenced by initOPL.
int16_t getEG()
function getter of the current general state (EG)
int16_t the current general state (EG)
References nbValuesCN_In_ByCN, values_In_CN_l.
statusErrDef isEGchanged()
function to check if the general state (EG) has been changed
statusErrDef infoModeSetToManual if the mode to manual order has been received from the MN or infoEGNotChanged if the EG is still the same.
References automatic, EC, EG, infoEGNotChanged, infoModeSetToManual, infoStateToManualMode, manual, mode, nbValuesCN_In_ByCN, resetTimers, values_In_CN_l.
Referenced by main.
void setEC(int16_t EC)
function setter of the board state (EC)
EC the board state (EC)
References EC, nbValuesCN_Out_ByCN, values_Out_CN_l.
statusErrDef initOPL()
function to initialize the CN OpenPOWERLINK module
statusErrDef that values errOPLSystemInit when OpenPOWERLINK fails to set the correct configuration for the current operating system. or errSelNetInterface when the selection of the network interface fails when in a Windows machine. Can be caused by the absence of WinPcap. or errInitObjDictionary when the object dictionary header file (objdict.h) has incorrect values or syntax. or errOplkInit when The OpenPOWERLINK stack fails to initialize, main cause: the stack is not found by the application, check the CN .lib files or errOplkCreate when the OpenPOWERLINK stack fails to create a new instance or errOplkAllocProcessImage when the allocation of the input and/or output structure fails because parts of the structure doesn't exist in the objdict.h file or errLinkPDOout when an output object (TPDO) doesn't exist for the same reasons above or errLinkPDOin when an input object (RPDO) doesn't exist for the same reasons above or errSendNMTResetCommand when the OpenPOWERLINK reset command fails or noError when the function exits successfully.
References aMacAddr_l, CYCLE_LEN, DEVNAME, tOptions::devName, errOPLSystemInit, fGsOff_l, initEvents, initOplThread, initPowerlink, initProcessImage, tOptions::logCategory, tOptions::logFormat, tOptions::logLevel, NODEID, tOptions::nodeId, noError, setActivated_Out_CN.
Referenced by main.
statusErrDef initPowerlink(UINT32 cycleLen_p, const char *devName_p, const UINT8 *macAddr_p, UINT32 nodeId_p)
Initialize the openPOWERLINK stack.
The function initializes the openPOWERLINK stack. cycleLen_p Length of POWERLINK cycle. devName_p Device name string. macAddr_p MAC address to use for POWERLINK interface. nodeId_p POWERLINK node ID. statusErrDef that values errSelNetInterface when the selection of the network interface fails when in a Windows machine can be caused by the absence of WinPcap. or errInitObjDictionary when the object dictionary header file (objdict.h) has incorrect values or syntax. or errOplkInit when the OpenPOWERLINK stack fails maybe because the stack is not found by the application, check the CN .lib files. or errOplkCreate when the OpenPOWERLINK stack fails to create a new instance or noError when the function exits successfully.
References DEFAULT_GATEWAY, errInitObjDictionary, errOplkCreate, errOplkInit, errSelNetInterface, IP_ADDR, noError, processEvents, processSync, SUBNET_MASK.
Referenced by initOPL.
statusErrDef initOplThread(void)
It creates the sync thread which is responsible for the synchronous data application. statusErrDef that values errSendNMTResetCommand when the OpenPOWERLINK reset command fails or noError when the function exits successfully.
References errSendNMTResetCommand, noError, setupInputs.
Referenced by initOPL.
statusErrDef checkStateOpl()
function to check if the OpenPOWERLINK stack crashed or a termination signal has been received from the OS app manager.
statusErrDef that values errSystemSendTerminate if a termination signal has been received or errOplKernelStackDown if the OpenPOWERLINK stack crashed or noError when the function exits successfully.
References errOplKernelStackDown, errSystemSendTerminate, noError.
Referenced by main.
tOplkError processSync()
Synchronous data handler.
The function implements the synchronous data handler. the valve dependance verification and the sensor reading is called here to trigger valves for every CAC boards (every CNs) at the same time. The function returns a tOplkError error code.
References activated_Out_CN_l, automatic, i, PI_IN::in_CN_array, manual, mode, nbValuesCN_In, nbValuesCN_In_ByCN, nbValuesCN_Out, nbValuesCN_Out_ByCN, PI_OUT::out_CN_array, pProcessImageIn_l, pProcessImageOut_l, readChannels, setValues_Out_CN, SIZE_IN, values_In_CN_l, values_Out_CN_l, valve::verifDependanceValves.
Referenced by initPowerlink.
void setupInputs(void)
Setup inputs.
The function initializes the digital input port.
References values_In_CN_l.
Referenced by initOplThread.
statusErrDef initProcessImage(void)
Initialize process image.
The function initializes the process image of the application. statusErrDef that values errOplkAllocProcessImage when the allocation of the input and/or output structure doesn't exist in the objdict.h file or errLinkPDOout when an output object (TPDO) doesn't exist for the same reasons above. or errLinkPDOin when an input object (RPDO) doesn't exist for the same reasons above. or noError when the function exits successfully.
References activated_Out_CN_l, errLinkPDOin, errLinkPDOout, errOplkAllocProcessImage, i, linkPDO_in, linkPDO_out, nbValuesCN_In, nbValuesCN_In_ByCN, nbValuesCN_Out, nbValuesCN_Out_ByCN, NODEID, noError, pProcessImageIn_l, pProcessImageOut_l.
Referenced by initOPL.
tOplkError linkPDO_in(tObdSize obdSize, UINT16 arrayIndex, UINT16 index, UINT8 subIndex)
function to link a CN RPDO (recieved process data object) gotten from the mnobd.cdc binary file generated by OpenCONFIGURATOR to the OpenPOWERLINK application.
obdSize the size of the PDO in bytes arrayIndex the index of the CN RPDO array index the index of the CN RPDO in the OpenPOWERLINK object library gotten from this file: 00000000_POWERLINK_CiA401_CN.xdd subIndex the sub index of the specific object to be linked gotten from this file: 00000000_POWERLINK_CiA401_CN.xdd The function returns a tOplkError error code.
Referenced by initProcessImage.
tOplkError linkPDO_out(tObdSize obdSize, UINT16 arrayIndex, UINT16 index, UINT8 subIndex)
function to link a CN TPDO (transmitted process data object) gotten from the mnobd.cdc binary file generated by OpenCONFIGURATOR to the OpenPOWERLINK application.
obdSize the size of the PDO in bytes arrayIndex the index of the CN TPDO array index the index of the CN RPDO in the OpenPOWERLINK object library gotten from this file: 00000000_POWERLINK_CiA401_CN.xdd subIndex the sub index of the specific object to be linked gotten from this file: 00000000_POWERLINK_CiA401_CN.xdd The function returns a tOplkError error code.
Referenced by initProcessImage.
statusErrDef extinctOPL()
function to shutdown the OpenPOWERLINK module.
statusErrDef that values errOplkFreeProcessImage when the freeing of memory of the OpenPOWERLINK stack fails. or noError when the function exits successfully.
References noError, shutdownOplImage, shutdownPowerlink.
Referenced by main.
statusErrDef shutdownOplImage(void)
Shutdown the synchronous data application.
The function shuts down the synchronous data application statusErrDef that values errOplkFreeProcessImage when the freeing of memory of the OpenPOWERLINK fails. or noError when the function exits successfully.
References errOplkFreeProcessImage, noError.
Referenced by extinctOPL.
void shutdownPowerlink(void)
Shutdown the demo application.
The function shuts down the demo application.
References fGsOff_l, i.
Referenced by extinctOPL.