sensor.cpp
int i
the for loops index
Referenced by valve::actionnementValvesInit, affValeursIn, affValeursOut, affValeursProcessIn, closeAdc, sensor::extinctSensor, valve::extinctValve, getDependanceVannes, getValvesInitValue, initProcessImage, sensor::initSensor, valve::initValve, valve::isDependanceActive, processSync, readChannels, removeCarriageReturn, remplirStructure, resetTimers, searchEG, setActivated_Out_CN, setValues_Out_CN, setValvesValue, shutdownPowerlink, valve::verifDependanceValves.
int num
number of modbus register read
Referenced by sensor::initSensor, readChannels.
uint8_t tabSensorActivated[MAX_SENSORS][MAX_SENSORS]
MCP3008 channels activation array.
Referenced by sensor::initSensor, readChannels, sensor::sensor.
int fd[MAX_SENSORS][MAX_SENSORS]
sysfs channel file array
Referenced by closeAdc, openAdc, readAdc, readChannels.
int16_t valSensors[MAX_SENSORS][MAX_SENSORS]
sensor values array
Referenced by getAdc_value, sensor::initSensor, readChannels.
modbus_t* ctx[MAX_SENSORS][MAX_SENSORS]
modbus instance array
Referenced by sensor::extinctSensor, sensor::initSensor, readChannels.
uint16_t modbusReg[MODBUS_NBREG][MODBUS_NBREG]
modbus registers read array
Referenced by sensor::initSensor, readChannels.
bool rs485Connected[MAX_SENSORS][MAX_SENSORS]
modbus sensor connexion boolean array, true if a modbus sensor is connected, false otherwise
Referenced by sensor::initSensor, readChannels.
int16_t getAdc_value(int index)
function getter of the value of a sensor from the array of sensors.
index the index of the array of sensors the value of the sensor in 2 bytes signed.
References valSensors.
Referenced by setValues_Out_CN.
statusErrDef readChannels()
function the read the channels of the MCP3008 by opening, reading and closing the sysfs files.
statusErrDef that values errOpenAdc when a sysfs file of the MCP3008 fails to open or errReadAdc when a sysfs file read of the MCP3008 fails or noError when the function exits successfully.
References ADC_READ_ERROR, closeAdc, ctx, errOpenAdc, errReadAdc, fd, getModbusStartAddress, getSensorType, i, MAX_ADC, MAX_SENSORS, MODBUS_NBREG, modbusReg, noError, num, openAdc, readAdc, rs485Connected, tabSensorActivated, valSensors.
Referenced by sensor::initSensor, processSync.
statusErrDef closeAdc()
function to close the sysfs files of the MCP3008 kernel module.
statusErrDef that values errCloseAdc when a sysfs file of the MCP3008 fails to close or noError when the function exits successfully.
References errCloseAdc, fd, i, MAX_ADC, noError.
Referenced by sensor::extinctSensor, readChannels.
int readAdc(int fd)
function to read the value of a sensor from a sysfs file of the MCP3008 kernel module.
fd the file location ADC_READ_ERROR when the file reading fails or the value of a sensor.
References ADC_READ_ERROR, fd.
Referenced by readChannels.
int openAdc(int adc)
function to open a sysfs file of the MCP3008 kernel module.
adc the MCP3008 channel number ADC_READ_ERROR when the file opening fails or the file location.
References ADC_READ_ERROR, fd, IIOSYSPATH.
Referenced by readChannels.