sensor.h
int16_t valSensors[MAX_SENSORS][MAX_SENSORS]
Referenced by getAdc_value, readChannels.
statusErrDef readChannels()
function the read the channels of the MCP3008 by opening, reading and closing the sysfs files.
statusErrDef that values errOpenAdc when a sysfs file of the MCP3008 fails to open or errReadAdc when a sysfs file read of the MCP3008 fails or noError when the function exits successfully.
References ADC_READ_ERROR, closeAdc, errOpenAdc, errReadAdc, fd, i, MAX_SENSORS, noError, openAdc, readAdc, tabSensorActivated, valSensors.
Referenced by sensor::initSensor, main.
statusErrDef closeAdc()
function to close the sysfs files of the MCP3008 kernel module.
statusErrDef that values errCloseAdc when a sysfs file of the MCP3008 fails to close or noError when the function exits successfully.
References errCloseAdc, fd, i, MAX_SENSORS, noError.
Referenced by sensor::extinctSensor, readChannels.
int readAdc(int fd)
function to read the value of a sensor from a sysfs file of the MCP3008 kernel module.
fd the file location ADC_READ_ERROR when the file reading fails or the value of a sensor.
References ADC_READ_ERROR, fd.
Referenced by readChannels.
int openAdc(int adc)
function to open a sysfs file of the MCP3008 kernel module.
adc the MCP3008 channel number ADC_READ_ERROR when the file opening fails or the file location.
References adc, ADC_READ_ERROR, fd, IIOSYSPATH.
Referenced by readChannels.
int16_t getAdc_value(int index)
function getter of the value of a sensor from the array of sensors.
index the index of the array of sensors the value of the sensor in 2 bytes signed.
References valSensors.
Referenced by setValues_Out_CN.