valve.h
int16_t setValvesValue()
function setter of the valve values from a general state CSV file.
0 if the valves are set successfully
References getActivation, getValeur, i, MAX_VALVES, nbValuesCN_In_ByCN, nbValuesCN_Out_ByCN, values.
statusErrDef getValvesInitValue()
function getter of the initial valve values from the valve physical config CSV file.
statusErrDef that values errGetValveInitValue when the getter of the initial values fails or noError when the function exits successfully.
References errGetValveInitValue, getActivation, getEtatInitialVannes, i, MAX_VALVES, nbValuesCN_Out_ByCN, noError, values.
Referenced by valve::extinctValve, valve::initValve.
int16_t getValveValue(int index)
function getter of the valve value from a general state CSV file on Windows or directly from the gpio line value on Linux.
ligne the line in a general state CSV file the value of the valve
References getValeur, nbValuesCN_In.
Referenced by setValues_Out_CN.
statusErrDef resetTimers()
function to reset the timers after the activation of all the valves.
statusErrDef that values noError when the function exits successfully.
References currentTime, getActivation, i, MAX_VALVES, nbValuesCN_Out_ByCN, noError, timerStarted.
Referenced by isEGchanged.